name: Trigger gitboard monitoring
  
on: 
    push:
        branches:
            - test-ci

jobs:
    build:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
      		- run:
          		name: Build binary
          		command: mkdir build && cd build &&
							cmake .. && make && ./src/demo-run

