name: Trigger gitboard monitoring
  
on: 
    push:
        branches:
            - test-ci

jobs:
    build:
        runs-on: ubuntu-latest
	
        steps:
	- uses: actions/checkout@v3
 
   	- name: Building
    	  run: |
       	    mkdir build && cd build && cmake .. && make && ./src/demo-run
