name: Trigger gitboard monitoring
  
on: 
    push:
        branches:
            - test-ci

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: gitboard/monitor-job-action@main

