name: Trigger gitboard monitoring

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
